version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env.docker
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
