import type { Metadata } from 'next';
import { getLocale, setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import NextTopLoader from 'nextjs-toploader';

import AppProvider from '@/providers/app-provider';

import { allLocaleCodes, availableLocalesMap, defaultLocale } from '@/i18n/locales';

import { INTER, OPEN_SANS } from '@/lib/next-fonts';
import { cn } from '@/lib/utils';

import '@/styles/globals.css';

const fontClasses = cn(OPEN_SANS.variable, INTER.variable);

export const metadata: Metadata = {
  title: 'Next tRpc boilerplate',
  description: 'Generated by next tRpc boilerplate',
};

export default async function RootAppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  if (!allLocaleCodes.includes(locale)) {
    setRequestLocale(defaultLocale.code);

    return notFound();
  }

  const { langDir, hrefLang } = availableLocalesMap[locale] || defaultLocale;

  setRequestLocale(locale);

  return (
    <html lang={hrefLang} dir={langDir} suppressHydrationWarning>
      <body className={fontClasses}>
        <AppProvider>
          <NextTopLoader color="var(--primary)" />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
